version: '3.8'

services:
  web:
    build: .
    container_name: interview_system_backend
    ports:
      - "5000:5000"
    environment:
      - BIND_ADDRESS=0.0.0.0:5000
      - LOG_LEVEL=info
      - CELERY_WORKER_ACTIVE=true
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 512M

  celery_worker:
    build: .
    container_name: interview_system_celery_worker
    command: celery -A tasks.celery_app.celery_app worker --loglevel=info --autoscale=10,2
    environment:
      - CELERY_WORKER_ACTIVE=true
      - CELERY_MIN_AUTOSCALE=2
      - CELERY_MAX_AUTOSCALE=10
    env_file:
      - .env
    depends_on:
      - web
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 256M
